### ISSUE TITLE
css fix - tag hover 時 延伸的 toobar (只有disabled時) 會被其他 UI 擋住

### ISSUE THREAD

**Issue by lokpro** [Physton/sd-webui-prompt-all-in-one#33]
tag hover 時 延伸的 toobar
在disabled時, opacity <1 所以因為 z排列問題,
會被其他 UI 擋住

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/2010297/82e77a70-f9ae-4b87-b2c9-2dc7616aae6a)
在外面 hover 不到

因此需要在 .disabled 再設一次 z-index

```css
    &.disabled {
        opacity: 0.5;
        z-index: 100;
    }
```

ref: https://stackoverflow.com/questions/2837057/what-has-bigger-priority-opacity-or-z-index-in-browsers
